[features]
seeds = false
skip-lint = false

[programs.localnet]
earn_staking = "E7JsJuQWGaEYC34AkEv8dcmkKUxR1KqUnje17mNCuTiY"

[programs.devnet]
earn_staking = "E7JsJuQWGaEYC34AkEv8dcmkKUxR1KqUnje17mNCuTiY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/earn-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/earn-staking"]
